apiVersion: apps/v1
kind: Deployment
metadata:
  name: fofatafo
  labels:
    app: fofatafo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fofatafo
  template:
    metadata:
      labels:
        app: fofatafo
    spec:
      containers:
      - name: fofatafo
        image: qusakabi/fofatafo:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "250m"
            memory: "200Mi"
        envFrom:
        - configMapRef:
            name: fofatafo-config