apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fofatafo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: fofatafo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fofatafo
            port:
              number: 80
